import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";

/**
 * Low-level, plain-data PDF primitives — no `Vehicle`/`VehicleDetail` types
 * in any signature here. That's what makes this genuinely reusable by a
 * future report (a VDP spec-sheet PDF, etc.): the caller assembles page-
 * specific data into these generic shapes, this file only knows how to draw
 * a branded header/footer/table, nothing about vehicles or comparisons.
 * Vector text throughout (jspdf-autotable), not a DOM screenshot — reads as
 * an actual report, not a rasterized webpage.
 */

const PRIMARY_RGB: [number, number, number] = [31, 168, 60];
const INK_RGB: [number, number, number] = [28, 28, 28];
const MUTED_RGB: [number, number, number] = [144, 144, 144];

export function createBrandedDocument(): jsPDF {
  return new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
}

export function addHeader(doc: jsPDF, { title, subtitle, date }: { title: string; subtitle?: string; date: string }): number {
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(...PRIMARY_RGB);
  doc.rect(0, 0, pageWidth, 22, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("EV Motion", 14, 13);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(date, pageWidth - 14, 13, { align: "right" });

  let y = 32;
  doc.setTextColor(...INK_RGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(title, 14, y);
  y += 7;

  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(...MUTED_RGB);
    doc.text(subtitle, 14, y);
    y += 6;
  }

  return y + 3;
}

export function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setTextColor(...PRIMARY_RGB);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(title, 14, y);
  return y + 5;
}

export function addBodyText(doc: jsPDF, text: string, y: number): number {
  doc.setTextColor(...INK_RGB);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  const pageWidth = doc.internal.pageSize.getWidth();
  const lines = doc.splitTextToSize(text, pageWidth - 28);
  doc.text(lines, 14, y);
  return y + lines.length * 5 + 4;
}

function getFinalY(doc: jsPDF, fallback: number): number {
  const withTable = doc as unknown as { lastAutoTable?: { finalY: number } };
  return withTable.lastAutoTable?.finalY ?? fallback;
}

export function addSectionTable(
  doc: jsPDF,
  { columns, rows, startY }: { columns: string[]; rows: (string | number)[][]; startY: number },
): number {
  autoTable(doc, {
    startY,
    head: [columns],
    body: rows,
    theme: "grid",
    margin: { left: 14, right: 14 },
    styles: { fontSize: 8.5, textColor: INK_RGB, cellPadding: 2 },
    headStyles: { fillColor: PRIMARY_RGB, textColor: [255, 255, 255], fontSize: 9, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [246, 247, 249] },
  });
  return getFinalY(doc, startY + 10) + 8;
}

/** Adds a new page if the given content height wouldn't fit before the footer margin. Returns the (possibly reset) y cursor. */
export function ensureSpace(doc: jsPDF, y: number, neededHeight = 30): number {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + neededHeight > pageHeight - 15) {
    doc.addPage();
    return 20;
  }
  return y;
}

export function addFooter(doc: jsPDF): void {
  const pageCount = doc.getNumberOfPages();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED_RGB);
    doc.text("Generated by EVMotion.in", 14, pageHeight - 8);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 8, { align: "right" });
  }
}
